spring.application.name=CryotoMtlsServerApplication

server.port=8443
# keystore for server TLS
server.ssl.key-store=${SERVER_SSL_KEY_STORE:C:/mtls-project/root/keystore/server_keystore.p12}
server.ssl.key-store-password=${SERVER_SSL_KEY_STORE_PASSWORD:changeit}
server.ssl.key-store-type=${SERVER_SSL_KEY_STORE_TYPE:PKCS12}
server.ssl.key-alias=server

# CA files (support classpath default for dev or env-path for runtime)
app.security.mtls-ca-cert-path=${APP_MTLS_CA_CERT:C:/mtls-project/root/root_cas/mtls_root_ca.cert.pem}
app.security.mtls-ca-key-path=${APP_MTLS_CA_KEY:C:/mtls-project/root/private_keys/mtls_root_ca.key.pem}
app.security.signing-ca-cert-path=${APP_SIGNING_CA_CERT:C:/mtls-project/root/root_cas/signing_root_ca.cert.pem}
app.security.signing-ca-key-path=${APP_SIGNING_CA_KEY:C:/mtls-project/root/private_keys/signing_root_ca.key.pem}